// Random starship data that is added to Firestore
// After you've signed in, click the dropdown
// menu in the top right corner and select "Add sample starships"

export const randomData = {
  starshipNames: [
    "USS Enterprise",
    "Serenity",
    "Millennium Falcon",
    "Nostromo",
    "Battlestar Galactica",
    "Rocinante",
    "Normandy SR-2",
    "Endurance",
    "Discovery One",
    "White Star",
    "Voyager",
    "Defiant",
    "Prometheus",
    "Eagle Five",
    "Event Horizon",
    "Sulaco",
    "Tardis",
    "Heart of Gold",
    "Andromeda Ascendant",
    "Agamemnon",
    "Hyperion",
    "Odysseus",
    "Icarus",
    "Atlas",
    "Orion",
    "Pegasus",
    "Titan",
    "Ares",
    "Zeus",
    "Apollo",
    "Artemis",
    "Hermes",
    "Poseidon",
    "Helios",
    "Nyx",
    "Eos",
    "Selene",
    "Aurora",
    "Nebula Drifter",
    "Star Runner",
    "Void Seeker",
    "Cosmic Wanderer",
  ],
  starshipManufacturers: [
    "Weyland-Yutani Corp",
    "Tyrell Industries",
    "Starfleet",
    "Martian Congressional Republic",
    "Blue Sun Corporation",
    "Cerberus",
    "Nerv",
    "InGen",
    "Umbrella Corporation",
    "Aperture Science",
    "Vault-Tec",
    "Hyperion Corporation",
    "Encom",
    "Omni Consumer Products",
    "Genetics General",
    "Stellar Dynamics",
    "Quantum Shipyards",
    "Nova Industries",
    "Titan Fleetworks",
    "Orbital Manufacturing",
  ],
  starshipClasses: [
    "Cruiser",
    "Destroyer",
    "Freighter",
    "Fighter",
    "Dreadnought",
    "Scout",
    "Carrier",
    "Explorer",
    "Battleship",
    "Corvette",
    "Frigate",
    "Interceptor",
    "Transport",
    "Research Vessel",
  ],
  starshipReviews: [
    { text: "Exceptional starship, absolutely outstanding engineering!", rating: 5 },
    { text: "Impressive warp drive and excellent life support systems!", rating: 5 },
    { text: "The engine performance was incredible, so smooth.", rating: 5 },
    { text: "Great shield systems and friendly crew quarters.", rating: 5 },
    { text: "A delightful spacefaring experience!", rating: 5 },
    {
      text: "Perfect maneuverability that left me wanting more flight time.",
      rating: 5,
    },
    { text: "Perfectly calibrated systems and stellar navigation.", rating: 5 },
    { text: "Incredible design and top-notch weaponry systems.", rating: 5 },
    { text: "Good cargo capacity and comfortable living spaces.", rating: 4 },
    { text: "Enjoyed piloting it, would fly again.", rating: 4 },
    { text: "Solid ship and reasonable production costs.", rating: 4 },
    { text: "Decent performance, but the systems were just okay.", rating: 3 },
    { text: "Average experience, but nothing extraordinary.", rating: 3 },
    { text: "The engines were average, could be more powerful.", rating: 3 },
    {
      text: "Systems were slow, and the shields were disappointing.",
      rating: 2,
    },
    { text: "Expected more, but left unsatisfied with performance.", rating: 2 },
    { text: "Underwhelming speed and lackluster weaponry.", rating: 2 },
    { text: "Disappointing experience overall.", rating: 2 },
    {
      text: "The ship was terrible, will never pilot again.",
      rating: 1,
    },
    {
      text: "Worst starship experience I've had so far.",
      rating: 1,
    },
    { text: "Avoid this model, the systems were unreliable.", rating: 1 },
    { text: "Unpleasant design and malfunctioning systems.", rating: 1 },
    { text: "Simply outstanding! A stellar engineering masterpiece.", rating: 5 },
    { text: "Couldn't get enough of the amazing warp capabilities.", rating: 5 },
    { text: "Top-notch quality, worth every cor.", rating: 5 },
    { text: "Highly recommended for space enthusiasts.", rating: 5 },
    { text: "Exquisite design that pleased my piloting needs.", rating: 5 },
    { text: "A gem of a ship, impeccable in every aspect.", rating: 5 },
    { text: "Excellent selection of advanced systems.", rating: 5 },
    { text: "A fantastic starship experience overall.", rating: 5 },
    {
      text: "The interior was lovely, perfect for long space journeys.",
      rating: 4,
    },
    { text: "Good performance, but the navigation could be improved.", rating: 4 },
    {
      text: "Pleasantly surprised by the variety of ship systems.",
      rating: 4,
    },
    { text: "Well-engineered systems and reliable components.", rating: 4 },
    { text: "Satisfying performance, suitable for short trips.", rating: 4 },
    { text: "The ship was okay, nothing special.", rating: 3 },
    {
      text: "Systems could be better, but the engines were fine.",
      rating: 3,
    },
    {
      text: "An average experience, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more value for the production cost.", rating: 2 },
    { text: "Mediocre performance and lackluster design.", rating: 2 },
    {
      text: "Regret spending cor on such a disappointing starship.",
      rating: 2,
    },
    { text: "Not up to par with my expectations.", rating: 2 },
  ],
};
